/* File generated with Shader Minifier 1.1.5
 * http://www.ctrl-alt-test.fr
 */
#ifndef GFX_H_
# define GFX_H_
# define VAR_IFONT "y"
# define VAR_IFONTWIDTH "x"
# define VAR_IRESOLUTION "m"
# define VAR_ITIME "v"

const char *gfx_frag =
 "#version 130\n"
 "uniform float v;"
 "uniform vec2 m;"
 "uniform sampler2D y;"
 "uniform float x;"
 "const vec3 f=vec3(1.,0.,-1.);"
 "const float z=acos(-1.);"
 "float i=1.,s=1.;"
 "vec2 r=f.yy,a=f.yy;"
 "float n(vec2 v)"
 "{"
   "return fract(sin(dot(v-1.,vec2(12.9898,78.233)))*43758.5);"
 "}"
 "float t(vec2 v)"
 "{"
   "vec2 x=floor(v);"
   "v=fract(v);"
   "float y=-1.+2.*n(x),z=-1.+2.*n(x+f.xy),m=-1.+2.*n(x+f.yx),s=-1.+2.*n(x+f.xx);"
   "return mix(mix(y,z,v.x),mix(m,s,v.x),v.y);"
 "}"
 "float n(vec2 v,float m,float y,float x)"
 "{"
   "float z=0.,f=1.2;"
   "for(float i=m;i<y;i=i*2.)"
     "z=f*t(i*v)+z,f=f*x;"
   "return z;"
 "}"
 "vec4 n(vec4 f,vec4 v)"
 "{"
   "return vec4(min(f.x,v.x),mix(v.yzw,f.yzw,smoothstep(-1.5/m.y,1.5/m.y,v.x)));"
 "}"
 "float n(vec2 v,vec2 y,vec2 m)"
 "{"
   "vec2 f=m-y;"
   "return length(v-mix(y,m,clamp(dot(v-y,f)/dot(f,f),0.,1.)));"
 "}"
 "float t(vec2 v,float x)"
 "{"
   "return length(v)-x;"
 "}"
 "float t(vec2 f,float y,float v,float x)"
 "{"
   "float i=atan(f.y,f.x);"
   "i=clamp(i,v,x);"
   "return length(f-y*vec2(cos(i),sin(i)));"
 "}"
 "float p(vec2 v,float x)"
 "{"
   "return min(min(t(v+x*f.zy,x),n(v,x*f.yz,x*f.yx)),t(v+x*f.xy,x,-.5*z,.5*z));"
 "}"
 "float h(float v,float x)"
 "{"
   "return abs(v)-x;"
 "}"
 "float h(vec2 v,vec2 y,vec2 x,vec2 f,float i)"
 "{"
   "return i=clamp(i,0.,1.),length(f-pow(1.-i,2.)*v-2.*(1.-i)*i*y-i*i*x);"
 "}"
 "float h(in vec2 v)"
 "{"
   "return dot(v,v);"
 "}"
 "float h(vec2 v,vec2 m,vec2 x,vec2 y)"
 "{"
   "vec2 i=min(v,min(m,x)),a=max(v,max(m,x)),r=(i+a)*.5,l=(a-i)*.5;"
   "float d=h(max(abs(y-r)-l,0.));"
   "if(d>s)"
     "return s;"
   "vec2 w=y-v,c=x-2.*m+v,t=m-v;"
   "vec3 n=vec3(3.*dot(t,c),2.*dot(t,t)-dot(w,c),-dot(w,t))/dot(c,c);"
   "float p=n.x/3.,g=n.y-p*n.x,e=-p*(p*p+g)+n.z,o=e*e/4.+g*g*g/27.;"
   "if(o>0.)"
     "{"
       "vec2 u=-.5*e*f.xx+sqrt(o)*f.xz,b=sign(u)*pow(abs(u),f.xx/3.);"
       "return h(v,m,x,y,b.x+b.y-p);"
     "}"
   "float u=sqrt(-4./3.*g),b=acos(-.5*e*sqrt(-27./g/g/g))/3.;"
   "vec3 q=f.zxz*u*cos(b*f.xxx+f*z/3.)-p;"
   "return min(h(v,m,x,y,q.x),min(h(v,m,x,y,q.y),h(v,m,x,y,q.z)));"
 "}"
 "float p(float v)"
 "{"
   "float f=mod(v,2.);"
   "v*=.5;"
   "vec2 i=(vec2(mod(v,x),floor(v/x))+.05)/x;"
   "vec4 m=texture(y,i);"
   "vec2 s=mix(m.xy,m.zw,f);"
   "return round(dot(vec2(255.,65280.),s));"
 "}"
 "float l(vec2 v,int m)"
 "{"
   "if(m==32)"
     "return a=i*vec2(.02,1.),1.;"
   "float x=p(0.),y=-1.;"
   "for(float r=0.;r<x;r+=1.)"
     "{"
       "int s=int(p(1.+2.*r));"
       "if(s==m)"
         "{"
           "y=p(1.+2.*r+1);"
           "break;"
         "}"
     "}"
   "if(y==-1.)"
     "return 1.;"
   "vec2 s=mix(f.xx,f.zz,vec2(p(y),p(y+2.)))*vec2(p(y+1.),p(y+3.));"
   "float z=p(y+4.),c=y+5.,r=y+6.+z,t=y+7.+2.*z,b=y+8.+3.*z,l=p(b-1.),w=1.;"
   "vec2 u=-100.*f.xx,d=100.*f.xx;"
   "for(float g=0.;g<l;g+=1.)"
     "{"
       "float e=0.,q=p(b+g);"
       "if(g>0.)"
         "e=p(b+g-1.)+1.;"
       "vec2 o[3];"
       "float F[3];"
       "int k=0;"
       "for(float C=e;C<=q;C+=1.)"
         "{"
           "F[k]=p(t+C);"
           "o[k]=(vec2(p(c+C),p(r+C))+s)/65536.*i;"
           "u=max(u,o[k]);"
           "d=min(d,o[k]);"
           "++k;"
           "if(k==2)"
             "{"
               "if(F[0]*F[1]==1)"
                 "w=min(w,n(v,o[0],o[1])),--C,k=0;"
             "}"
           "else"
             " if(k==3)"
               "{"
                 "if(F[0]*F[2]==1.)"
                   "w=min(w,h(o[0],o[1],o[2],v)),--C,k=0;"
                 "else"
                   "{"
                     "vec2 D=mix(o[1],o[2],.5);"
                     "w=min(w,h(o[0],o[1],D,v));"
                     "o[0]=D;"
                     "F[0]=1.;"
                     "u=max(u,o[0]);"
                     "d=min(d,o[0]);"
                     "--C;"
                     "k=1;"
                   "}"
               "}"
         "}"
       "F[k]=p(t+e);"
       "o[k]=(vec2(p(c+e),p(r+e))+s)/65536.*i;"
       "u=max(u,o[0]);"
       "d=min(d,o[0]);"
       "++k;"
       "if(k==2)"
         "w=min(w,n(v,o[0],o[1]));"
       "else"
         " if(k==3)"
           "w=min(w,h(o[0],o[1],o[2],v));"
     "}"
   "a=abs(u-d);"
   "return w;"
 "}"
 "float d(vec2 v,int m)"
 "{"
   "float x=p(0.),y=-1.;"
   "for(float r=0.;r<x;r+=1.)"
     "{"
       "int w=int(p(1.+2.*r));"
       "if(w==m)"
         "{"
           "y=p(1.+2.*r+1);"
           "break;"
         "}"
     "}"
   "if(y==-1.)"
     "return 1.;"
   "vec2 s=mix(f.xx,f.zz,vec2(p(y),p(y+2.)))*vec2(p(y+1.),p(y+3.));"
   "float z=p(y+4.),o=y+5.,w=y+6.+z,r=1.;"
   "for(float u=0.;u<z;u+=1.)"
     "{"
       "vec2 d=(vec2(p(o+u),p(w+u))+s)/65536.*i;"
       "r=min(r,length(v-d)-.002);"
     "}"
   "return r;"
 "}"
 "mat2 d(float v)"
 "{"
   "vec2 m=vec2(cos(v),sin(v));"
   "return mat2(m*f.xz,m.yx);"
 "}"
 "float w(float y,float x)"
 "{"
   "return smoothstep(y-.5,y+.5,v)*(1.-smoothstep(x-.5,x+.5,v));"
 "}"
 "void e(out vec4 y,in vec2 x)"
 "{"
   "vec2 s=x/m.yy-.5;"
   "vec3 o=f.yyy;"
   "if(v<6.)"
     "{"
       "vec4 u=vec4(1.,o);"
       "float z=1.,c=1.,k=1.;"
       "vec2 g=.02*vec2(t(2.3*s-2.*vec2(1.5,2.4)*v),t(1.7*s-2.4*vec2(1.2,2.1)*v));"
       "{"
         "i=1.54;"
         "r=-.25*f.xy;"
         "int F[17]=int[17](72,101,108,108,111,44,32,86,111,114,116,101,120,32,73,73,73);"
         "for(int e=0;e<17;++e)"
           "{"
             "if(abs(s.x)<1.5&&abs(s.y)<.1)"
               "{"
                 "vec2 b=s-r-g+.05*f.yx;"
                 "z=min(z,l(b,F[e]));"
                 "float q=d(b,F[e]);"
                 "c=min(c,q);"
                 "k=min(k,h(q,.002));"
                 "r+=a.x*f.xy+.01*f.xy;"
               "}"
           "}"
       "}"
       "z=h(z,.0024)+.1*length(g);"
       "u=n(u,vec4(z,f.xxx));"
       "u=n(u,vec4(k,f.xxx));"
       "u=n(u,vec4(c,f.xyy));"
       "o=u.yzw*smoothstep(1.5/m.y,-1.5/m.y,u.x)*w(1.,5.);"
     "}"
   "else"
     " if(v<1000.)"
       "{"
         "float u=v-6.;"
       "}"
   "o=mix(clamp(o,f.yyy,f.xxx),f.xxx,smoothstep(1.5/m.y,-1.5/m.y,h(p(s-vec2(-.45,.45),.02),.005)));"
   "y=vec4(o,1.);"
 "}"
 "void main()"
 "{"
   "e(gl_FragColor,gl_FragCoord.xy);"
 "}";

#endif // GFX_H_
