/* File generated with Shader Minifier 1.1.5
 * http://www.ctrl-alt-test.fr
 */
#ifndef GFX_H_
# define GFX_H_
# define VAR_IFONT "y"
# define VAR_IFONTWIDTH "x"
# define VAR_IRESOLUTION "f"
# define VAR_ITIME "v"

const char *gfx_frag =
 "#version 130\n"
 "uniform float v;"
 "uniform vec2 f;"
 "uniform sampler2D y;"
 "uniform float x;"
 "const vec3 m=vec3(1.,0.,-1.);"
 "const float s=acos(-1.);"
 "float i=1.,l=1.;"
 "vec2 r=m.yy,a=m.yy;"
 "float n(vec2 v)"
 "{"
   "return fract(sin(dot(v-1.,vec2(12.9898,78.233)))*43758.5);"
 "}"
 "float t(vec2 v)"
 "{"
   "vec2 x=floor(v);"
   "v=fract(v);"
   "float f=-1.+2.*n(x),y=-1.+2.*n(x+m.xy),p=-1.+2.*n(x+m.yx),i=-1.+2.*n(x+m.xx);"
   "return mix(mix(f,y,v.x),mix(p,i,v.x),v.y);"
 "}"
 "float n(vec2 v,float m,float y,float x)"
 "{"
   "float i=0.,p=1.2;"
   "for(float f=m;f<y;f=f*2.)"
     "i=p*t(f*v)+i,p=p*x;"
   "return i;"
 "}"
 "vec4 n(vec4 v,vec4 m)"
 "{"
   "return vec4(min(v.x,m.x),mix(m.yzw,v.yzw,smoothstep(-1.5/f.y,1.5/f.y,m.x)));"
 "}"
 "float n(vec2 v,vec2 f,vec2 m)"
 "{"
   "vec2 x=m-f;"
   "return length(v-mix(f,m,clamp(dot(v-f,x)/dot(x,x),0.,1.)));"
 "}"
 "float t(float v,float x)"
 "{"
   "return abs(v)-x;"
 "}"
 "float n(vec2 v,vec2 m,vec2 x,vec2 f,float p)"
 "{"
   "return p=clamp(p,0.,1.),length(f-pow(1.-p,2.)*v-2.*(1.-p)*p*m-p*p*x);"
 "}"
 "float d(in vec2 v)"
 "{"
   "return dot(v,v);"
 "}"
 "float d(vec2 v,vec2 p,vec2 x,vec2 f)"
 "{"
   "vec2 i=min(v,min(p,x)),y=max(v,max(p,x)),r=(i+y)*.5,z=(y-i)*.5;"
   "float a=d(max(abs(f-r)-z,0.));"
   "if(a>l)"
     "return l;"
   "vec2 w=f-v,t=x-2.*p+v,c=p-v;"
   "vec3 h=vec3(3.*dot(c,t),2.*dot(c,c)-dot(w,t),-dot(w,c))/dot(t,t);"
   "float k=h.x/3.,g=h.y-k*h.x,e=-k*(k*k+g)+h.z,o=e*e/4.+g*g*g/27.;"
   "if(o>0.)"
     "{"
       "vec2 u=-.5*e*m.xx+sqrt(o)*m.xz,b=sign(u)*pow(abs(u),m.xx/3.);"
       "return n(v,p,x,f,b.x+b.y-k);"
     "}"
   "float u=sqrt(-4./3.*g),b=acos(-.5*e*sqrt(-27./g/g/g))/3.;"
   "vec3 q=m.zxz*u*cos(b*m.xxx+m*s/3.)-k;"
   "return min(n(v,p,x,f,q.x),min(n(v,p,x,f,q.y),n(v,p,x,f,q.z)));"
 "}"
 "float p(float v)"
 "{"
   "float m=mod(v,2.);"
   "v*=.5;"
   "vec2 f=(vec2(mod(v,x),floor(v/x))+.05)/x;"
   "vec4 p=texture(y,f);"
   "vec2 i=mix(p.xy,p.zw,m);"
   "return round(dot(vec2(255.,65280.),i));"
 "}"
 "float d(vec2 v,int f)"
 "{"
   "if(f==32)"
     "return a=i*vec2(.02,1.),1.;"
   "float x=p(0.),y=-1.;"
   "for(float r=0.;r<x;r+=1.)"
     "{"
       "int u=int(p(1.+2.*r));"
       "if(u==f)"
         "{"
           "y=p(1.+2.*r+1);"
           "break;"
         "}"
     "}"
   "if(y==-1.)"
     "return 1.;"
   "vec2 r=mix(m.xx,m.zz,vec2(p(y),p(y+2.)))*vec2(p(y+1.),p(y+3.));"
   "float u=p(y+4.),t=y+5.,c=y+6.+u,b=y+7.+2.*u,o=y+8.+3.*u,l=p(o-1.),w=1.;"
   "vec2 z=-100.*m.xx,g=100.*m.xx;"
   "for(float s=0.;s<l;s+=1.)"
     "{"
       "float h=0.,q=p(o+s);"
       "if(s>0.)"
         "h=p(o+s-1.)+1.;"
       "vec2 e[3];"
       "float k[3];"
       "int F=0;"
       "for(float C=h;C<=q;C+=1.)"
         "{"
           "k[F]=p(b+C);"
           "e[F]=(vec2(p(t+C),p(c+C))+r)/65536.*i;"
           "z=max(z,e[F]);"
           "g=min(g,e[F]);"
           "++F;"
           "if(F==2)"
             "{"
               "if(k[0]*k[1]==1)"
                 "w=min(w,n(v,e[0],e[1])),--C,F=0;"
             "}"
           "else"
             " if(F==3)"
               "{"
                 "if(k[0]*k[2]==1.)"
                   "w=min(w,d(e[0],e[1],e[2],v)),--C,F=0;"
                 "else"
                   "{"
                     "vec2 D=mix(e[1],e[2],.5);"
                     "w=min(w,d(e[0],e[1],D,v));"
                     "e[0]=D;"
                     "k[0]=1.;"
                     "z=max(z,e[0]);"
                     "g=min(g,e[0]);"
                     "--C;"
                     "F=1;"
                   "}"
               "}"
         "}"
       "k[F]=p(b+h);"
       "e[F]=(vec2(p(t+h),p(c+h))+r)/65536.*i;"
       "z=max(z,e[0]);"
       "g=min(g,e[0]);"
       "++F;"
       "if(F==2)"
         "w=min(w,n(v,e[0],e[1]));"
       "else"
         " if(F==3)"
           "w=min(w,d(e[0],e[1],e[2],v));"
     "}"
   "a=abs(z-g);"
   "return w;"
 "}"
 "float p(vec2 v,int x)"
 "{"
   "float f=p(0.),y=-1.;"
   "for(float r=0.;r<f;r+=1.)"
     "{"
       "int w=int(p(1.+2.*r));"
       "if(w==x)"
         "{"
           "y=p(1.+2.*r+1);"
           "break;"
         "}"
     "}"
   "if(y==-1.)"
     "return 1.;"
   "vec2 r=mix(m.xx,m.zz,vec2(p(y),p(y+2.)))*vec2(p(y+1.),p(y+3.));"
   "float w=p(y+4.),e=y+5.,t=y+6.+w,z=1.;"
   "for(float u=0.;u<w;u+=1.)"
     "{"
       "vec2 g=(vec2(p(e+u),p(t+u))+r)/65536.*i;"
       "z=min(z,length(v-g)-.003);"
     "}"
   "return z;"
 "}"
 "mat2 h(float v)"
 "{"
   "vec2 f=vec2(cos(v),sin(v));"
   "return mat2(f*m.xz,f.yx);"
 "}"
 "void h(out vec4 w,in vec2 x)"
 "{"
   "vec2 y=x/f.yy-.5;"
   "vec3 e=m.yyy;"
   "if(v<1000.)"
     "{"
       "vec4 z=vec4(1.,e);"
       "float u=1.,g=1.;"
       "vec2 F=.02*vec2(t(2.3*y-2.*vec2(1.5,2.4)*v),t(1.7*y-2.4*vec2(1.2,2.1)*v));"
       "{"
         "i=1.54;"
         "r=-.25*m.xy;"
         "int k[17]=int[17](72,101,108,108,111,44,32,86,111,114,116,101,120,32,73,73,73);"
         "for(int h=0;h<17;++h)"
           "u=min(u,d(y-r-F,k[h])),g=min(g,p(y-r-F,k[h])),r+=a.x*m.xy+.01*m.xy;"
       "}"
       "u=t(u,.002)+.1*length(F);"
       "z=n(z,vec4(u,m.xxx));"
       "z=n(z,vec4(g,m.xyy));"
       "e=z.yzw*smoothstep(1.5/f.y,-1.5/f.y,z.x);"
     "}"
   "w=vec4(e,1.);"
 "}"
 "void main()"
 "{"
   "h(gl_FragColor,gl_FragCoord.xy);"
 "}";

#endif // GFX_H_
